
flowchart TD
    A[Step 1. ReadtheDocs.org] -->|Select| B[Voyager Academy]
    B --> |Select| C[Build version]
    C --> D{Result}
    D --> |Success| E[View Academy]
    D --> |Error| F[Call Support]
    D --> |Error| G[Refresh Page]
